name: Bug Report
description: Report a bug in YT Desktop
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened?
    validations:
      required: true
  - type: dropdown
    id: platform
    attributes:
      label: Platform
      options: [Windows, Linux]
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: From Settings or --version
